---
# tasks file for kubernetes-minion
- name: flush handlers
  meta: flush_handlers
- name: install kubernetes
  package: name=kubernetes state=latest
- name: configure kubernetes
  template: src=etc/kubernetes/config dest=/etc/kubernetes/config owner=root group=root mode="a=rw,g=r,o=r"
- name: configure kubelet
  template: src=etc/kubernetes/kubelet dest=/etc/kubernetes/kubelet owner=root group=root mode="a=rw,g=r,o=r"
  notify:
    - restart kubelet
    - restart kube-proxy
- name: start kube-proxy
  service: name=kube-proxy state=started enabled=true
- name: start kubelet
  service: name=kubelet state=started enabled=true
