---
# tasks file for kubernetes-master
- name: flush handlers
  meta: flush_handlers
- name: install ntpd
  package: name=ntp state=latest
- name: start ntpd
  service: name=ntpd state=started enabled=true
- name: install kubernetes
  package: name=kubernetes state=latest
- name: configure apiserver
  template: src=etc/kubernetes/apiserver dest=/etc/kubernetes/apiserver owner=root group=root mode="a=rw,g=r,o=r"
  notify: restart apiserver
- name: start apiserver
  service: name=kube-apiserver state=started enabled=true
- name: start controller-manager
  service: name=kube-controller-manager state=started enabled=true
- name: start scheduler
  service: name=kube-scheduler state=started enabled=true
- name: flanneld configuration
  uri:
    url: "{{kube_etcd_server}}/v2/keys{{flanneld_network_key}}/config"
    method: PUT
    body: "value={\"Network\": \"172.17.0.0/16\"}"
    status_code: 200,201
